### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Weroxig** [LiteralGenie/ocr_data#1]
also, do you think you could make a fork of https://github.com/kha-white/mokuro for Korean using your OCR model? Their model only supports Japanese but maybe contents of mokuro/manga_page_ocr.py could be changed to use your model?

**Comment by LiteralGenie** [comment]
Added an MIT license, thanks for the reminder!

**Comment by LiteralGenie** [comment]
> also, do you think you could make a fork of https://github.com/kha-white/mokuro for Korean using your OCR model?

Sure, I gave it a go here: https://github.com/LiteralGenie/mokuro

Preview video:

https://github.com/user-attachments/assets/42f3eb83-0752-4551-9234-37d98f3459d6

HTML file: https://files.catbox.moe/iqhir4.html
mokuro (json) file: https://files.catbox.moe/khn13j.mokuro

---

To run it:
```bash
git clone git@github.com:LiteralGenie/mokuro.git
cd mokuro/
git submodule init
git submodule update

python3 -m venv venv
. ./venv/bin/activate
pip install .

mokuro data/test_1/
```

Note that I updated the [defaults](https://github.com/LiteralGenie/mokuro/blob/6fafbdafc461ca9008d51ff04e6393802cec516c/mokuro/run.py#L18) to point to the [v1 weights](https://github.com/LiteralGenie/comic_ocr/releases/tag/v1.0.0) that have been checked into that fork.  

So if you're planning to run `mokuro` from outside the repo folder, you'll have to manually set `--det_weights=whatever/db_resnet50.pt` and `--reco_weights=whatever/parseq.pt`.

---

Also can I ask what the use-case is @Weroxig ? Are you planning to use this with a yomichan-like extension for Korean? Or did you just want the json output or something.

**Comment by Weroxig** [comment]
> Sure, I gave it a go here: https://github.com/LiteralGenie/mokuro

Cool, thanks, I'll go check that out.
> Also can I ask what the use-case is @Weroxig ? Are you planning to use this with a yomichan-like extension for Korean? Or did you just want the json output or something.

I'm using it with [yomitan](https://github.com/themoeway/yomitan/)
